# Writes OUT (build_info.hpp) with the git commit of SRC and whether the
# working tree had uncommitted changes to tracked files. Rewrites the file only
# when it changes, so unchanged builds do not recompile its users.
execute_process(COMMAND git -C "${SRC}" rev-parse HEAD
                OUTPUT_VARIABLE GIT_COMMIT OUTPUT_STRIP_TRAILING_WHITESPACE
                RESULT_VARIABLE GIT_RC ERROR_QUIET)
if(NOT GIT_RC EQUAL 0)
  set(GIT_COMMIT "unknown")
endif()
execute_process(COMMAND git -C "${SRC}" status --porcelain --untracked-files=no
                OUTPUT_VARIABLE GIT_STATUS ERROR_QUIET)
if(GIT_STATUS STREQUAL "")
  set(GIT_DIRTY "false")
else()
  set(GIT_DIRTY "true")
endif()

set(CONTENT "#pragma once

// Generated by cmake/build_info.cmake at build time.
namespace build_info {
inline constexpr const char *kGitCommit = \"${GIT_COMMIT}\";
inline constexpr bool kGitDirty = ${GIT_DIRTY};
} // namespace build_info
")
if(EXISTS "${OUT}")
  file(READ "${OUT}" OLD)
endif()
if(NOT OLD STREQUAL CONTENT)
  file(WRITE "${OUT}" "${CONTENT}")
endif()
